server:
  config:
    secrets:
      password-secret: PeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G
      token-hash-secret: QfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&E)H

  port: 8080

google:
  base-url: https://storage.googleapis.com
  credentials: /sa-private-key.json
  projectId: pharmacist-420716
  bucketName: pharmacist-g03

spring:
  application:
    name: pharmacist

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true

# Set debug log level
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
        data: INFO
    com:
      pharmacist: INFO
    root: info
