name: Continuous Integration

on: [ push ]

jobs:
  docker:
    name: Docker Compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
